### ISSUE TITLE
NOt working

### ISSUE THREAD

**Issue by rajeshksoni11** [MannLabs/alphapeptstats#267]
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\rs3869\AppData\Local\Programs\AlphaPeptStats\alphastats\gui\AlphaPeptStats.py", line 8, in <module>
    from utils.ui_helper import sidebar_info, img_to_bytes
  File "C:\Users\rs3869\AppData\Local\Programs\AlphaPeptStats\alphastats\gui\utils\ui_helper.py", line 4, in <module>
    from alphastats import __version__
ModuleNotFoundError: No module named 'alphastats'

**Comment by JuliaS92** [comment]
If this issue still exists, could you please specify, how you tried to execute alphapeptstats (executable/from code) and in which environment (OS/python environment/source branch)? Otherwise we can't address the issue.
