### ISSUE TITLE
Precompiled Windows binary won't run because of missing files in the build

### ISSUE THREAD

**Issue by andzajan** [MannLabs/alphapeptstats#380]
Release 0.6.9 https://github.com/MannLabs/alphapeptstats/releases/download/v0.6.9/alphastats_gui_installer_windows.exe

When I try to run error output is related to Pyinstaller configuration:

λ alphastats_gui.exe
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pkg_resources\__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "jaraco\text\__init__.py", line 231, in <module>
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AlphaPeptStats\\jaraco\\text\\Lorem ipsum.txt'
[21636] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

**Comment by mschwoer** [comment]
Hey, thanks for reaching out.

Sorry for the late reply, we've been working on a new release for the couple of months, which is now ready: https://github.com/MannLabs/alphapeptstats/releases/tag/v0.7.0

Please check if your issue still occurs.

best,
Magnus
