### ISSUE TITLE
cannot launch Alphastats in MacBookPro M2

### ISSUE THREAD

**Issue by alexsykaras** [MannLabs/alphapeptstats#382]
Hi, I just download it AlphaStats but cannot open it

**Version (please complete the following information):**
 - OS: MacOS
 - Version Sonoma 14.6.1
 - Installation Type: One-Click Installer

**Additional context**
Copied from Terminal

Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "pkg_resources/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "jaraco/text/__init__.py", line 231, in <module>
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/AlphaPeptStats.app/Contents/MacOS/jaraco/text/Lorem ipsum.txt'
[9526] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Thank you!
Alexandros

**Comment by JuliaS92** [comment]
Thank you for letting us know, we will look into it.

**Comment by mschwoer** [comment]
Hey, thanks for reaching out.

Sorry for the late reply, we've been working on a new release for the couple of months, which is now ready: https://github.com/MannLabs/alphapeptstats/releases/tag/v0.7.0

Please check if your issue still occurs.

best,
Magnus
